### PR TITLE
Update hiring.md

### PR DESCRIPTION
**Pull request by tonypecc**

### CODE REVIEW

**Comment by tonypecc** [comment]
I think that it is comforting to know that someone will get to meet with all of the people they are going to be working with directly.  I also think it is good for current employees to meet the candidates.

**Comment by bmuller** [comment]
@tonypecc I'm thinking of what this could mean logistically - specifically this bit:

> during the interview process you will have a chance to meet and talk with all of the people you will directly be working with

If there's a team of 3 (1 person in Seattle, 1 in Austin, and 1 in Miami) and they want to hire a 4th person in LA - would all 4 people be flown to a single location to meet each other as a part of the interview process?  Would that happen for every late stage candidate?  I think the "talk with" makes sense - but the "meet" might be super expensive and complex logistically.

**Comment by tonypecc** [comment]
Ah, I meant video calls to meet everyone with enough time for people to actually get to know each other.  Sort of like what we did with Alan.

**Comment by bmuller** [comment]
@tonypecc ahh ok that makes total sense.  What do think about something like:

> during the interview process you will have a chance to talk and virtually interact with all of the people you will directly be working with

Just to make it clear that candidates won't physically be meeting team members necessarily

**Comment by tonypecc** [comment]
yessir, I think that sounds perfect.  I am also enjoying this interaction on Git :)

**Pull request merged**
